config/routes.rb
DayStats::Application.routes.draw do
  get "pages/home"
  match "pages/display" => 'pages#display'

  root :to => 'pages#home'

end

app/views/layouts/_inputs.html.erb
 <div class="actions">
   <%= form_tag(pages_display_path, :method=>'post') do  %>
   
   symbol <br /> <%= text_field_tag 'stocksymbol', value=@user_input[:stocksymbol] %> <br />
    open price (if not filled in, will use Yahoo! opening price) <br /> <%= text_field_tag 'openprice', value=@user_input[:openprice] %>
    <table><tr>
  <td>
    lookback (number of days) <br /> <%= text_field_tag 'lookback', value=@user_input[:lookback] %>
      </td><td>
    lookfoward (number of days) <br /> <%= text_field_tag 'lookforward', value=@user_input[:lookforward] %>
      </td><td>
    period (how far back should the historical data start) <br /> <%= text_field_tag 'period', value=@user_input[:period] %>
      </td></tr></table>
     <%= submit_tag "display" , :name=> "display" %>
      
   <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Historical Chances <%= @user_input[:stocksymbol] %> </title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-18624381-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>
<body>

<%= yield %>

</body>
</html>